### ISSUE TITLE
ValueError in icon_button on macOS

### ISSUE THREAD

**Issue by dhyanKaro** [SamuLumio/object-settings#3]
If you run this code on osx:
```py
from tkinter import ttk
import tkinter
from settings_gui.ttk import SettingsWindow, enable_ttk
import settings
# Setting
settings.setup("test")
title = settings.Text("Title", 'Hello')
# GUI
enable_ttk()
root = tkinter.Tk()
settings_window = SettingsWindow(root, title="Wow")
root.mainloop()
```

You're gonna get this error:

```
Traceback (most recent call last):
  File "wow.py", line 11, in <module>
    settings_window = SettingsWindow(root, title="Wow")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/settings_gui/tkinter/main.py", line 42, in __init__
    SettingsFrame(self, autosave, save_button).pack(padx=config.padding*2, pady=config.padding*2, fill='both')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/settings_gui/tkinter/main.py", line 16, in __init__
    section_frame = section_frames.SectionFrame(self, section, autosave=autosave)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/settings_gui/tkinter/section_frames.py", line 17, in __init__
    self.settings.append(type_frame(self, setting, autosave=autosave))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/settings_gui/tkinter/type_frames.py", line 24, in __init__
    self.init()
  File "/usr/local/lib/python3.11/site-packages/settings_gui/tkinter/type_frames.py", line 146, in init
    self.done_button = lib.AppearingWidget(lib.icon_button(self, 'checkmark', self.save_from_widget))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/settings_gui/tkinter/lib.py", line 50, in icon_button
    rgb = tuple(int(hex[i:i + 2], 16) for i in (0, 2, 4))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/settings_gui/tkinter/lib.py", line 50, in <genexpr>
    rgb = tuple(int(hex[i:i + 2], 16) for i in (0, 2, 4))
                ^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: 'sy'
```

Because here, this line in lib.py:
```py
hex = a.layer.Style().lookup('TButton', 'background') # type: ignore
```
results in hex having the value "systemWindowBackgroundColor"

If you need anything else let me know I'll be here all day.

**Comment by SamuLumio** [comment]
I feared some incompatibility like this would come up. That code tries to determine which color of an icon to use, based on the shade of the background.

I've put in this bit to use that command on macos:
```
if platform.system() == 'Darwin':
    rgb = master.winfo_rgb('systemWindowBackgroundColor')
```

Could you install object-settings from this repo and see if it works?

**Comment by dhyanKaro** [comment]
Nice, it's better now.
subprocess isn't needed if you do `master._getints(master.tk.call('winfo', 'rgb', '.', 'systemWindowBackgroundColor'))`
But that's the same as `rgb = master.winfo_rgb('systemWindowBackgroundColor')` -- so better to use that.

Here are the rgb values I get on light and dark mode.
```
rgb = master.winfo_rgb('systemWindowBackgroundColor')
# on dark mode: (12850, 12850, 12850)
#   light mode: (60652, 60652, 60652)
```
They both give a dark check-mark:
![Screenshot 2023-10-30 at 10 34 35 AM](https://github.com/SamuLumio/object-settings/assets/112676875/f11df09c-def6-4809-9eb5-7e4772ad518c)
![Screenshot 2023-10-30 at 10 35 02 AM](https://github.com/SamuLumio/object-settings/assets/112676875/ea4416b0-967b-44be-832d-c19afc183ef4)

Probably because the lightness value.

I see that colorsys expects "All inputs and outputs are triples of **floats in the range [0.0...1.0]**"
We can divide, then check if brightness is is above 50%
```py
rgb = tuple(value / 65535.0 for value in rgb)
```
Looks good.
![Screenshot 2023-10-30 at 11 18 11 AM](https://github.com/SamuLumio/object-settings/assets/112676875/91e72154-16c1-4265-865d-21dbe8d38e57)

```py
def icon_button(master, icon_name: str, command):
	"""Generate a (normal or ttk) button with an icon of the correct color"""
	
	if a.is_ttk():
		if platform.system() == 'Darwin':
			rgb = master.winfo_rgb('systemWindowBackgroundColor')
			rgb = tuple(value / 65535.0 for value in rgb)
		else:
			hex = a.layer.Style().lookup('TButton', 'background')  # type: ignore
			hex = str(hex).removeprefix('#')
			rgb = tuple(int(hex[i:i + 2], 16) for i in (0, 2, 4))
		hls = colorsys.rgb_to_hls(*rgb)
		brightness = hls[1]
		color = 'black' if brightness > 0.5 else 'white'
	else:
		color = 'black'
```

Please test on windows too, as the RGB hex conversion line `rgb = tuple(int(hex[i:i + 2], 16) for i in (0, 2, 4))` may have to also be put in decimal form from 0 to 1

**Comment by SamuLumio** [comment]
Yeah, this seems to work universally after changing the conversion to produce a decimal too. Thank you very much! Committing this and closing the issue.

**Comment by samulumio** [comment]
If you ever have any more feature requests, don't hesitate to make an issue!
